### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by orblatt** [secrary/SSMA#53]
Hello, can you please aid with the following error?

Traceback (most recent call last):
  File "ssma.py", line 141, in <module>
	_tls = pe.checkTSL()
  File "/home/user/Downloads/SSMA-master/src/check_file.py", line 243, in checkTSL
	pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_TLS']].VirtualAddress
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
	from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
	from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
	import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
	from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
	import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
	import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "ssma.py", line 141, in <module>
	_tls = pe.checkTSL()
  File "/home/user/Downloads/SSMA-master/src/check_file.py", line 243, in checkTSL
	pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_TLS']].VirtualAddress
IndexError: list index out of range

**Comment by Evan-Sa** [comment]
Hello there can you verify that you have all the dependencies installed. If you do can you provide the sample that caused this exception to fire.

**Comment by Evan-Sa** [comment]
@orblatt  just wanted to follow up did you have any success getting it to work yet?
